= Installing Schelog

First, obtain the Schelog distribution:

  git clone https://github.com/ds26gte/schelog

This produces a directory called `schelog`.  This directory
contains, among other subsidiary files:

- the Schelog code file `schelog.scm`;

- the file `INSTALL.adoc`, which you are now reading.

❧

The file `schelog.scm` in the distribution loads in
Racket (and some other Scheme dialects) without
configuration.  If it does not load in your
dialect, you can configure Schelog for it using
the scmxlate package, which is available at
http://github.com/ds26gte/scmxlate.

Start your Scheme in the `schelog` directory, and load
the file `scmxlate/scmxlate.scm`, using the correct
relative or full pathname.  You will be asked what your
Scheme dialect is.  Answer appropriately.  The
following symbols are used by the porting
mechanism to identify the corresponding Scheme
dialects: `bigloo` (Bigloo); `gambit` (Gambit); `guile`
(Guile); `mitscheme` (MIT Scheme); `mzscheme` (MzScheme);
`petite` (Petite Chez Scheme); `pscheme` (Pocket Scheme);
`scm` (SCM); `stk` (STk).

scmxlate will generate a file called
`my-schelog.scm`, which you may rename to
`schelog.scm`.

Load `schelog.scm` into your Scheme in order to use
Schelog.

The distribution comes with an `examples` subdirectory
containing some sample Schelog programs.  In order to
try an example file, load it into your Scheme after
ensuring that `schelog.scm` has already been loaded.
Follow the instructions in the example file.

❧

The file `index.tex` contains a tutorial on Schelog.  Run it
through (plain) TeX to obtain viewable/printable
documentation.  (You will need to run TeX twice to resolve
cross references.)

You can get a browsable version of the document by
calling

  tex2page index.tex

This browsable version is also available for Web viewing at

  http://ds26gte.github.io/schelog/index.html

tex2page is available at

  github.com/ds26gte/tex2page

// Last modified: 2015-11-27
